[package]
name = "benches"
version = "0.1.0"
edition = "2024"

[dependencies]
storage = { path = "../storage" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }
tokio = { version = "1.44.2", features = ["full"] }

[[bench]]
name = "wal_bench"
harness = false
